Resources:
  TeamRole:
      Type: AWS::IAM::Role
      Properties: 
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
              Action: 
                - "sts:AssumeRole"
        ManagedPolicyArns:
          - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AWSServiceCatalogAdminFullAccess'
        Description: Team Role to test workshop content
        MaxSessionDuration: 43200
        RoleName: TeamRole
  TeamRolePolicy:    
      Type: "AWS::IAM::Policy"
      Properties:
          PolicyName: "MGT312"
          PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
                - 
                  Resource: "*"
                  Action: 
                    - "apigateway:*"
                    - "application-autoscaling:*"
                    - "applicationautoscaling:*"
                    - "appsync:*"
                    - "acm:*"
                    - "acm-pca:*"
                    - "appmesh:*"
                    - "appstream:*"
                    - "appsync:*"
                    - "arsenal:*"
                    - "artifact:*"
                    - "athena:*"
                    - "autoscaling-plans:*"
                    - "autoscaling:*"
                    - "awsconnector:*"
                    - "batch:*"
                    - "ce:*"
                    - "cloud9:*"
                    - "cloudformation:*"
                    - "cloudfront:*"
                    - "cloudmap:*"
                    - "cloudtrail:*"
                    - "cloudwatch:*"
                    - "codebuild:*"
                    - "codecommit:*"
                    - "codedeploy:*"
                    - "codepipeline:*"
                    - "codestar:*"
                    - "cognito-identity:*"
                    - "cognito-idp:*"
                    - "cognito-sync:*"
                    - "comprehend:*"
                    - "comprehendmedical:*"
                    - "config:*"
                    - "datapipeline:*"
                    - "datasync:*"
                    - "deepracer:*"
                    - "dms:*"
                    - "ds:*"
                    - "dynamodb:*"
                    - "ec2:*"
                    - "ec2messages:*"
                    - "ecr:*"
                    - "ecs:*"
                    - "eks:*"
                    - "elasticache:*"
                    - "elasticbeanstalk:*"
                    - "elasticfilesystem:*"
                    - "elasticloadbalancing:*"
                    - "elasticmapreduce:*"
                    - "emr:*"
                    - "es:*"
                    - "events:*"
                    - "execute-api:*"
                    - "firehose:*"
                    - "forecast:*"
                    - "fsx:*"
                    - "glacier:*"
                    - "globalaccelerator:*"
                    - "glue:*"
                    - "greengrass:*"
                    - "guardduty:*"
                    - "iam:*"
                    - "inspector:*"
                    - "iot:*"
                    - "iotanalytics:*"
                    - "kinesis:*"
                    - "kinesisanalytics:*"
                    - "kinesisanalyticsv2:*"
                    - "kinesisvideo:*"
                    - "kms:*"
                    - "lakeformation:*"
                    - "lambda:*"
                    - "lex:*"
                    - "lightsail:*"
                    - "logs:*"
                    - "macie:*"
                    - "managedblockchain:*"
                    - "mediaconvert:*"
                    - "medialive:*"
                    - "mediapackage:*"
                    - "mediastore:*"
                    - "mediatailor:*"
                    - "mgh:*"
                    - "mq:*"
                    - "personalize:*"
                    - "polly:*"
                    - "pricing:*"
                    - "qldb:*"
                    - "quicksight:*"
                    - "rds:*"
                    - "redshift:*"
                    - "rekognition:*"
                    - "resource-groups:*"
                    - "robomaker:*"
                    - "route53:*"
                    - "route53domains:DisableDomainAutoRenew"
                    - "route53domains:ListDomains"
                    - "s3:*"
                    - "sagemaker:*"
                    - "secretsmanager:*"
                    - "securityhub:*"
                    - "serverlessrepo:*"
                    - "servicecatalog:*"
                    - "servicediscovery:*"
                    - "sms:*"
                    - "sns:*"
                    - "sqs:*"
                    - "ssm:*"
                    - "ssmmessages:*"
                    - "states:*"
                    - "storagegateway:*"
                    - "sts:*"
                    - "tag:*"
                    - "textract:*"
                    - "transcribe:*"
                    - "transfer:*"
                    - "translate:*"
                    - "waf-regional:*"
                    - "waf:*"
                    - "xray:*"
                  Effect: "Allow"
                  Sid: "OverlyPermissivePolicy"
                - 
                  Condition: 
                      StringEquals: 
                          ec2:InstanceType: 
                            - "t2.nano"
                            - "t2.micro"
                            - "t2.small"
                            - "t3.nano"
                            - "t3.micro"
                            - "t3.small"
                  Resource: 
                    - "arn:aws:ec2:*:*:instance/*"
                  Action: "ec2:RunInstances"
                  Effect: "Allow"
                  Sid: "OnlyAllowT2andT3"
                - 
                  Resource: 
                    - "arn:aws:ec2:*::image/ami-*"
                    - "arn:aws:ec2:*:*:subnet/*"
                    - "arn:aws:ec2:*:*:network-interface/*"
                    - "arn:aws:ec2:*:*:volume/*"
                    - "arn:aws:ec2:*:*:key-pair/*"
                    - "arn:aws:ec2:*:*:security-group/*"
                  Action: "ec2:RunInstances"
                  Effect: "Allow"
                  Sid: "AllowAllTheOtherRunInstancesResources"
                - 
                  Resource: "*"
                  Action: 
                    - "ec2:Accept*"
                    - "ec2:Allocate*"
                    - "ec2:Assign*"
                    - "ec2:Associate*"
                    - "ec2:Attach*"
                    - "ec2:Authorize*"
                    - "ec2:Bundle*"
                    - "ec2:Cancel*"
                    - "ec2:Confirm*"
                    - "ec2:Copy*"
                    - "ec2:Create*"
                    - "ec2:Delete*"
                    - "ec2:Deregister*"
                    - "ec2:Describe*"
                    - "ec2:Detach*"
                    - "ec2:Disable*"
                    - "ec2:Disassociate*"
                    - "ec2:Enable*"
                    - "ec2:Get*"
                    - "ec2:Import*"
                    - "ec2:Modify*"
                    - "ec2:Monitor*"
                    - "ec2:Move*"
                    - "ec2:Reboot*"
                    - "ec2:Register*"
                    - "ec2:Reject*"
                    - "ec2:Release*"
                    - "ec2:Replace*"
                    - "ec2:Report*"
                    - "ec2:Reset*"
                    - "ec2:Restore*"
                    - "ec2:Revoke*"
                    - "ec2:Start*"
                    - "ec2:Stop*"
                    - "ec2:Terminate*"
                    - "ec2:Unassign*"
                    - "ec2:Unmonitor*"
                    - "ec2:Search*"
                  Effect: "Allow"
                  Sid: "AllowAllOtherEC2ActionsExceptSpotAndReserved"
                - 
                  Resource: "*"
                  Action: 
                    - "ec2:ModifyReservedInstances"
                    - "ec2:PurchaseHostReservation"
                    - "ec2:PurchaseReservedInstancesOffering"
                    - "ec2:PurchaseScheduledInstances"
                    - "rds:PurchaseReservedDBInstancesOffering"
                    - "dynamodb:PurchaseReservedCapacityOfferings"
                    - "ec2:CancelSpotFleetRequests"
                    - "ec2:ModifySpotFleetRequest"
                    - "ec2:RequestSpotFleet"
                    - "ec2:RequestSpotInstances"
                    - "ec2:CancelSpotInstanceRequests"
                    - "ec2:CreateSpotDatafeedSubscription"
                    - "ec2:DeleteSpotDatafeedSubscription"
                  Effect: "Deny"
                  Sid: "DontBuyReservationsOrSpotPlz"
                - 
                  Effect: "Allow"
                  Action: "sts:AssumeRole"
                  Resource: "arn:aws:iam::*:role/mgt312_sc_end_user_MGT312-IAMStack*"
                - 
                  Resource: "arn:aws:iam::024357338510:role/TeamRole"
                  Action: "iam:PassRole"
                  Effect: "Allow"
                  Sid: "PassRole"
          Roles: 
            - !Ref "TeamRole"