AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template creates the CloudEndure Policy
Resources:
  CloudEndureUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: CloudEndureUser
      ManagedPolicyArns: 
        - !Ref CloudEndurePolicy1
        - !Ref CloudEndurePolicy2
  CloudEndurePolicy1:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
        ManagedPolicyName: "CloudEndurePolicy"
        PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "ec2:CreateTags"
                Resource: "arn:aws:ec2:*:*:*/*"
                Condition: 
                    StringEquals: 
                        ec2:CreateAction: "RunInstances"
              - 
                Effect: "Allow"
                Action: "ec2:CreateTags"
                Resource: "arn:aws:ec2:*:*:*/*"
                Condition: 
                    StringEquals: 
                        ec2:CreateAction: "CreateVolume"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:RevokeSecurityGroupIngress"
                  - "ec2:DetachVolume"
                  - "ec2:AttachVolume"
                  - "ec2:DeleteVolume"
                  - "ec2:TerminateInstances"
                  - "ec2:StartInstances"
                  - "ec2:RevokeSecurityGroupEgress"
                  - "ec2:StopInstances"
                Resource: 
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                Condition: 
                    StringLike: 
                        ec2:ResourceTag/Name: "CloudEndure*"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:RevokeSecurityGroupIngress"
                  - "ec2:DetachVolume"
                  - "ec2:AttachVolume"
                  - "ec2:DeleteVolume"
                  - "ec2:TerminateInstances"
                  - "ec2:StartInstances"
                  - "ec2:RevokeSecurityGroupEgress"
                  - "ec2:StopInstances"
                Resource: 
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                Condition: 
                    StringLike: 
                        ec2:ResourceTag/CloudEndure creation time: "*"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:DisassociateAddress"
                  - "ec2:CreateDhcpOptions"
                  - "ec2:AuthorizeSecurityGroupIngress"
                  - "ec2:DeregisterImage"
                  - "ec2:DeleteSubnet"
                  - "ec2:DeleteSnapshot"
                  - "ec2:ModifyVolumeAttribute"
                  - "ec2:CreateVpc"
                  - "ec2:AttachInternetGateway"
                  - "ec2:GetConsoleScreenshot"
                  - "ec2:GetConsoleOutput"
                  - "elasticloadbalancing:DescribeLoadBalancers"
                  - "ec2:CreateRoute"
                  - "ec2:CreateInternetGateway"
                  - "ec2:CreateSecurityGroup"
                  - "ec2:CreateSnapshot"
                  - "ec2:ModifyVpcAttribute"
                  - "ec2:ModifyInstanceAttribute"
                  - "ec2:ReleaseAddress"
                  - "ec2:AuthorizeSecurityGroupEgress"
                  - "ec2:AssociateDhcpOptions"
                  - "ec2:ImportKeyPair"
                  - "ec2:CreateTags"
                  - "ec2:RegisterImage"
                  - "ec2:ModifyNetworkInterfaceAttribute"
                  - "ec2:CreateRouteTable"
                  - "ec2:DetachInternetGateway"
                  - "iam:ListInstanceProfiles"
                  - "ec2:AllocateAddress"
                  - "ec2:ReplaceNetworkAclAssociation"
                  - "ec2:CreateVolume"
                  - "kms:ListKeys"
                  - "ec2:Describe*"
                  - "ec2:DeleteVpc"
                  - "iam:GetUser"
                  - "ec2:CreateSubnet"
                  - "ec2:AssociateAddress"
                  - "ec2:DeleteKeyPair"
                  - "ec2:CreateNetworkAclEntry"
                Resource: "*"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:RevokeSecurityGroupIngress"
                  - "mgh:CreateProgressUpdateStream"
                  - "kms:Decrypt"
                  - "kms:Encrypt"
                  - "ec2:RevokeSecurityGroupEgress"
                  - "ec2:DeleteDhcpOptions"
                  - "ec2:RunInstances"
                  - "kms:DescribeKey"
                  - "kms:CreateGrant"
                  - "ec2:DeleteNetworkAclEntry"
                  - "kms:ReEncrypt*"
                  - "kms:GenerateDataKey*"
                Resource: 
                  - "arn:aws:mgh:*:*:progressUpdateStream/*"
                  - "arn:aws:ec2:*:*:subnet/*"
                  - "arn:aws:ec2:*:*:key-pair/*"
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*:*:network-acl/*"
                  - "arn:aws:ec2:*:*:placement-group/*"
                  - "arn:aws:ec2:*:*:vpc/*"
                  - "arn:aws:ec2:*:*:network-interface/*"
                  - "arn:aws:ec2:*::image/*"
                  - "arn:aws:ec2:*:*:snapshot/*"
                  - "arn:aws:kms:*:*:key/*"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:CreateTags"
                  - "mgh:ImportMigrationTask"
                  - "mgh:AssociateCreatedArtifact"
                  - "mgh:NotifyMigrationTaskState"
                  - "mgh:DisassociateCreatedArtifact"
                  - "mgh:PutResourceAttributes"
                Resource: 
                  - "arn:aws:mgh:*:*:progressUpdateStream/*/migrationTask/*"
                  - "arn:aws:ec2:*:*:subnet/*"
                  - "arn:aws:ec2:*::network-interface/*"
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*::snapshot/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*::image/*"
              - 
                Effect: "Allow"
                Action: "ec2:Delete*"
                Resource: 
                  - "arn:aws:ec2:*:*:route-table/*"
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*:*:internet-gateway/*"
                Condition: 
                    StringLike: 
                        ec2:ResourceTag/Name: "CloudEndure*"
              - 
                Sid: "VisualEditor8"
                Effect: "Allow"
                Action: "ec2:Delete*"
                Resource: 
                  - "arn:aws:ec2:*:*:route-table/*"
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*:*:internet-gateway/*"
                Condition: 
                    StringLike: 
                        ec2:ResourceTag/CloudEndure creation time: "*"
  CloudEndurePolicy2:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
        ManagedPolicyName: "CloudEndurePolicy2"
        PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "ec2:CreateTags"
                Resource: "arn:aws:ec2:*:*:*/*"
                Condition: 
                    StringEquals: 
                        ec2:CreateAction: "RunInstances"
              - 
                Effect: "Allow"
                Action: "ec2:CreateTags"
                Resource: "arn:aws:ec2:*:*:*/*"
                Condition: 
                    StringEquals: 
                        ec2:CreateAction: "CreateVolume"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:RevokeSecurityGroupIngress"
                  - "ec2:DetachVolume"
                  - "ec2:AttachVolume"
                  - "ec2:DeleteVolume"
                  - "ec2:TerminateInstances"
                  - "ec2:StartInstances"
                  - "ec2:RevokeSecurityGroupEgress"
                  - "ec2:StopInstances"
                Resource: 
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                Condition: 
                    StringLike: 
                        ec2:ResourceTag/Name: "CloudEndure*"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:RevokeSecurityGroupIngress"
                  - "ec2:DetachVolume"
                  - "ec2:AttachVolume"
                  - "ec2:DeleteVolume"
                  - "ec2:TerminateInstances"
                  - "ec2:StartInstances"
                  - "ec2:RevokeSecurityGroupEgress"
                  - "ec2:StopInstances"
                Resource: 
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                Condition: 
                    StringLike: 
                        ec2:ResourceTag/CloudEndure creation time: "*"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:DisassociateAddress"
                  - "ec2:CreateDhcpOptions"
                  - "ec2:AuthorizeSecurityGroupIngress"
                  - "ec2:DeregisterImage"
                  - "ec2:DeleteSubnet"
                  - "ec2:DeleteSnapshot"
                  - "ec2:ModifyVolumeAttribute"
                  - "ec2:CreateVpc"
                  - "ec2:AttachInternetGateway"
                  - "ec2:GetConsoleScreenshot"
                  - "ec2:GetConsoleOutput"
                  - "elasticloadbalancing:DescribeLoadBalancers"
                  - "ec2:CreateRoute"
                  - "ec2:CreateInternetGateway"
                  - "ec2:CreateSecurityGroup"
                  - "ec2:CreateSnapshot"
                  - "ec2:ModifyVpcAttribute"
                  - "ec2:ModifyInstanceAttribute"
                  - "ec2:ReleaseAddress"
                  - "ec2:AuthorizeSecurityGroupEgress"
                  - "ec2:AssociateDhcpOptions"
                  - "ec2:ImportKeyPair"
                  - "ec2:CreateTags"
                  - "ec2:RegisterImage"
                  - "ec2:ModifyNetworkInterfaceAttribute"
                  - "ec2:CreateRouteTable"
                  - "ec2:DetachInternetGateway"
                  - "iam:ListInstanceProfiles"
                  - "ec2:AllocateAddress"
                  - "ec2:ReplaceNetworkAclAssociation"
                  - "ec2:CreateVolume"
                  - "kms:ListKeys"
                  - "ec2:Describe*"
                  - "ec2:DeleteVpc"
                  - "iam:GetUser"
                  - "ec2:CreateSubnet"
                  - "ec2:AssociateAddress"
                  - "ec2:DeleteKeyPair"
                  - "ec2:CreateNetworkAclEntry"
                Resource: "*"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:RevokeSecurityGroupIngress"
                  - "mgh:CreateProgressUpdateStream"
                  - "kms:Decrypt"
                  - "kms:Encrypt"
                  - "ec2:RevokeSecurityGroupEgress"
                  - "ec2:DeleteDhcpOptions"
                  - "ec2:RunInstances"
                  - "kms:DescribeKey"
                  - "kms:CreateGrant"
                  - "ec2:DeleteNetworkAclEntry"
                  - "kms:ReEncrypt*"
                  - "kms:GenerateDataKey*"
                Resource: 
                  - "arn:aws:mgh:*:*:progressUpdateStream/*"
                  - "arn:aws:ec2:*:*:subnet/*"
                  - "arn:aws:ec2:*:*:key-pair/*"
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*:*:network-acl/*"
                  - "arn:aws:ec2:*:*:placement-group/*"
                  - "arn:aws:ec2:*:*:vpc/*"
                  - "arn:aws:ec2:*:*:network-interface/*"
                  - "arn:aws:ec2:*::image/*"
                  - "arn:aws:ec2:*:*:snapshot/*"
                  - "arn:aws:kms:*:*:key/*"
              - 
                Effect: "Allow"
                Action: 
                  - "ec2:CreateTags"
                  - "mgh:ImportMigrationTask"
                  - "mgh:AssociateCreatedArtifact"
                  - "mgh:NotifyMigrationTaskState"
                  - "mgh:DisassociateCreatedArtifact"
                  - "mgh:PutResourceAttributes"
                Resource: 
                  - "arn:aws:mgh:*:*:progressUpdateStream/*/migrationTask/*"
                  - "arn:aws:ec2:*:*:subnet/*"
                  - "arn:aws:ec2:*::network-interface/*"
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*::snapshot/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*::image/*"
              - 
                Effect: "Allow"
                Action: "ec2:Delete*"
                Resource: 
                  - "arn:aws:ec2:*:*:route-table/*"
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*:*:internet-gateway/*"
                Condition: 
                    StringLike: 
                        ec2:ResourceTag/Name: "CloudEndure*"
              - 
                Effect: "Allow"
                Action: "ec2:Delete*"
                Resource: 
                  - "arn:aws:ec2:*:*:route-table/*"
                  - "arn:aws:ec2:*:*:dhcp-options/*"
                  - "arn:aws:ec2:*:*:instance/*"
                  - "arn:aws:ec2:*:*:volume/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*:*:internet-gateway/*"
                Condition: 
                    StringLike: 
                        ec2:ResourceTag/CloudEndure creation time: "*"
